### ISSUE TITLE
Error in Current Wedge Fraction Obstructions

### ISSUE THREAD

**Issue by paullewisn** [danopstech/starlink#34]
`docker-compose pull && docker-compose up`

Shows an error in the CWFO panel

![image](https://github.com/danopstech/starlink/assets/15159310/7cb0f44a-e05e-479c-95c0-ade4596f350d)

```
There's an error in your script :
TypeError: Cannot read properties of undefined (reading 'fields') - line 3:28 (Check your console for more details)
```

```
runRequest.catchError {"type":"cancelled","cancelled":true,"data":null,"status":-1,"statusText":"Request was aborted","config":{"method":"GET","url":"api/annotations","params":{"from":1684339656956,"to":1684341456956,"limit":100,"matchAny":false,"dashboardUID":"GG3mnflGz"},"requestId":"grafana-data-source-annotations-Annotations & Alerts-GG3mnflGz","retry":0,"headers":{"X-Grafana-Org-Id":1},"hideFromInspector":true}}
overrideMethod @ react_devtools_backend_compact.js:2367
```

```
Gauge rendering error Error: Invalid dimensions for plot, width = 0, height = 74
    at n.resize (jquery.flot.js:136:13)
    at new n (jquery.flot.js:114:10)
    at jquery.flot.js:1326:17
    at new s (jquery.flot.js:714:5)
    at e.plot (jquery.flot.js:3296:16)
    at v.draw (Gauge.tsx:140:9)
    at v.componentDidUpdate (Gauge.tsx:51:10)
    at ps (react-dom.production.min.js:219:502)
    at Au (react-dom.production.min.js:259:160)
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
```

**Comment by bonJoeV** [comment]
@dwillcocks I have the same issue.

**Comment by istrait** [comment]
I also have this issue

**Comment by NOTORIOUSVR** [comment]
Same issue - deployed today

**Comment by Felzow47** [comment]
same issue !
