### ISSUE TITLE
kwargs_from_env() got an unexpected keyword argument 'ssl_version'

### ISSUE THREAD

**Issue by Bluemethyst** [danopstech/starlink#37]
**Describe the bug**
When trying to start the program for the first time, this error occurred and program stopped.
```Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'
```

**To Reproduce**
Git clone repo
run `docker-compose pull && docker-compose up --remove-orphan` as specified in README

**Expected behavior**
Expected program to start

**Screenshots**
![image](https://github.com/danopstech/starlink/assets/88925092/dbc2bac5-9bce-448e-a51b-65739926eae1)

**Additional context**
 - OS: Raspberry Pi OS

**Comment by sburquest** [comment]
This might be helpful
https://stackoverflow.com/questions/77641240/getting-docker-compose-typeerror-kwargs-from-env-got-an-unexpected-keyword-ar
